### ISSUE TITLE
Collaborators登録お願いします

### ISSUE THREAD

**Issue by SakodaShintaro** [saitokok/paraview#3]
Forkだと面倒臭そうなのでコCollaborators登録してpushできるようにお願いします

手順
https://reasonable-code.com/github-collaborators/

**Comment by ksato-dev** [comment]
@saitokok 
FYI: @SakodaShintaro 
上記対応お願いします。

**Comment by ksato-dev** [comment]
slack より。
```
[SaitKoki]
マージしました。
コラボレータにしてもいいんですが、全員のアカウント把握してないんで、随時対応になります
Folkだと面倒なんですかね？
```

**Comment by SakodaShintaro** [comment]
* 自分のところにリポジトリ増やしたくない
* 更新の際のキャッチアップがやや面倒そう

と思いましたが、まぁ自前でやりますか……
